[build]
  command = "npm run build"

[[headers]]
  for = "/qr-code-component/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'none'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/nft-preview-card-component/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'none'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/equalizer-landing-page/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'none'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/order-summary-component/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'none'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/advice-generator/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'self'; connect-src https://api.adviceslip.com/advice; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/stats-preview-card/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'none'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/ping-coming-soon-page/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'self'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/preview-card-component/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'self'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/faq-accordion-card/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'self'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/expenses-chart-component/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'self'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/skilled-elearning-landing-page/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'self'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"

[[headers]]
  for = "/product-preview-card-component/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; form-action 'none'; script-src 'self'; connect-src 'none'; img-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; require-trusted-types-for 'script';"
