import "./globals.css";
import { Jost } from "next/font/google";

const jost = Jost({ subsets: ["latin"], variable: "--font-jost" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={jost.variable}>{children}</body>
    </html>
  );
}
